---
development:
  NEWS_API_KEY: <NEWS_API_KEY>
  SEC_API_KEY: <SEC_API_KEY>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

test:
  NEWS_API_KEY: <NEWS_API_KEY>
  SEC_API_KEY: <SEC_API_KEY>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>
  
production:
  NEWS_API_KEY: <NEWS_API_KEY>
  SEC_API_KEY: <SEC_API_KEY>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>